
import Header from "@/components/header";
import "./globals.css";
import { Providers } from "./providers";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <body className={"antialiased font-mono"}>
        <Providers>
          <div className="flex min-h-screen flex-col bg-neutral-900 text-base font-normal text-white w-full">
            <Header /> 
              {children} 
            <Footer/>
          </div> 
        </Providers>
      </body>
    </html>
  );
}
