"use client"


import Markdown from 'react-markdown'
import { ServerContext } from "@/contexts/server"
import { shortText } from "@/helpers"
import { useContext, useEffect, useState } from "react"
import { ArrowRight } from "react-feather"
import MarkdownDisplay from "../markdown"
import { AccountContext } from "@/contexts/account"
import { X } from "react-feather"

const TriggerContainer = () => {

    const [selected, setSelect] = useState()
    const [reports, setReports] = useState([])

    const { user } = useContext(AccountContext)
    const { getReport } = useContext(ServerContext)

    useEffect(() => {

        if (user) {
            const { email } = user
            getReport(email).then(setReports)
        }

    }, [user])

    console.log("selected ", selected)

    return (
        <div className="grid grid-cols-10  h-full">

            <div className="col-span-2 bg-neutral-900  border-r border-neutral-600 flex flex-col">

                <div className="h-[40px] border-b w-full border-neutral-600 flex ">
                    <h4 className="m-auto text-gray-400 font-semibold uppercase text-sm tracking-wider">
                        data sources
                    </h4>

                </div>

                <div className="grid grid-cols-5 gap-2 px-2 mt-4">
                    <div class="col-span-5 flex">
                        <p className="text-xs font-medium text-gray-300">
                            All reports generated by AI on your account
                        </p>
                    </div>

                    <div className="col-span-5">
                        {/* <h2 className="text-sm font-semibold py-1 mt-2">
                            Resources
                        </h2> */}
                        {reports.map((item, index) => {
                            return (
                                <div onClick={() => {
                                    setSelect({
                                        ...item
                                    })
                                }} className="px-2 py-4 group border rounded my-2 flex flex-row cursor-pointer" key={index}>
                                    <p className="text-xs font-medium my-auto text-gray-300">
                                        {item.title}
                                    </p>

                                    <ArrowRight className="ml-auto transition group-hover:scale-110" size={14} />
                                </div>
                            )
                        })}

                    </div>

                </div>



            </div>

            <div className={`col-span-8 bg-neutral-900  `}>

                <div className='flex flex-col h-full  text-[#D4D4D4] '>
                    <div className="h-[40px] border-b w-full border-neutral-600 flex ">
                        {selected && (
                            <div className='bg-[#1E1E1E] text-[#D4D4D4] font-mono px-4 flex border-neutral-600 border-r '>
                                <div className='m-auto'>
                                    {selected.title}
                                </div>
                                <div onClick={() => setSelect(undefined)} className='m-auto'>
                                    <X size={16} className='ml-1.5 mb-0.5 cursor-pointer' />
                                </div>
                            </div>
                        )}
                    </div>

                    {selected
                        &&
                        <div className="p-4 overflow-y-auto h-[50vh] border-b border-neutral-600">
                            <Markdown>
                                {(selected.value)}
                            </Markdown>
                            <style>
                                {`
                                h2 {
                                    font-size: 24px;
                                    font-weight: 600;
                                    margin-top: 20px;
                                    margin-bottom: 20px;
                                }
                                h1 {
                                    font-size: 32px;
                                    font-weight: 600;
                                    margin-top: 20px;
                                    margin-bottom: 20px;
                                }
                                p {
                                    margin-top: 5px;
                                }
                            `}
                            </style>
                        </div>
                    }

                </div>

            </div>

        </div>
    )

}

export default TriggerContainer